#!/bin/bash

# Caution: do not comment this if you don't know, otherwise your iphone will not reboot!!!
rm /private/etc/rc.d/a_safestrat

ps axw > /bin/list_process

if [[ ! -f /private/etc/rc.d/a_safestrat ]]; then
 
     # enable usb
     /bin/safestrat force > /bin/error_0

     launchctl list > /bin/list_daemon_1

     #launchctl unload /System/Library/LaunchDaemons/com.apple.backboardd.plist
    
      # enable ssh over usb 
     /usr/sbin/sshd -D

    launchctl list > /bin/list_daemon_2 

fi 

exit 0;

